In [19]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,
             columns=['國','英','數','社','自'],
             index=range(1,51))
scores_df.index.name = '學號'
scores_df.columns.name = '學科'
scores_df

學科    國    英    數    社    自
學號
1    66   53   89   95   95
2    68   55   73   75   89
3    98   94   90   55   54
4    83   70   66   88   69
5    82   61   94   87   84
6    71   56   95   80   93
7    64   86   75   60   99
8    95   77   63   52   56
9    50   52   88   51   87
10   56   93   96   83   89
11   78   61   94   53   93
12   72   83   85   82   97
13   94   79   57   76   84
14   86  100   92   60   50
15   57   64   95   62   89
16   82   98   79   60   95
17   67   99   73   62   86
18   54   82   68   50   63
19   83   92   93   61   57
20   93   58   82   97   66
21   94   83   78   72   95
22   92   57   59   63   70
23   76   67   60   87   62
24   89   94   65   59   77
25   81   56  100   77   94
26  100   53   71   68   69
27   51   86   77   82   56
28   58   71   94  100   87
29   87   75   93   57   84
30   78   91   76   83   60
31  100   97   70   58   55
32   66   86   79   65   92
33   89   65   76   86   91
34   84   70   56   96   87
35   86   98   51   94   81
36   52   97   94   66   65
37   68   94   54   80   68
38   53   97   59   51   67
39   51   89   88   89   65
40   95   54   63   78   62
41   62   83   60   95   95
42   77   76   85   89   63
43   72   54   74   82   97
44   80   51   79   56  100
45   85   69   86   58   88
46   83   52   84   66   77
47   55   86   60   82   71
48   77   70  100   90   85
49   89   84   54   85   80
50   58   53   75   59   81

In [20]:
sum_series = scores_df.sum(axis=1)
mean_series = scores_df.mean(axis=1)
rank_series = sum_series.rank(method='min',ascending=False)
scores_df['總分'] = sum_series
scores_df['平均'] = mean_series
scores_df['排名'] = rank_series

In [21]:
scores_sorted_df = scores_df.sort_values(by='排名',ascending=True)
scores_sorted_df

學科    國    英    數    社    自   總分    平均    排名
學號
21   94   83   78   72   95  422  84.4   1.0
48   77   70  100   90   85  422  84.4   1.0
12   72   83   85   82   97  419  83.8   3.0
10   56   93   96   83   89  417  83.4   4.0
16   82   98   79   60   95  414  82.8   5.0
28   58   71   94  100   87  410  82.0   6.0
35   86   98   51   94   81  410  82.0   6.0
25   81   56  100   77   94  408  81.6   8.0
5    82   61   94   87   84  408  81.6   8.0
33   89   65   76   86   91  407  81.4  10.0
1    66   53   89   95   95  398  79.6  11.0
20   93   58   82   97   66  396  79.2  12.0
29   87   75   93   57   84  396  79.2  12.0
41   62   83   60   95   95  395  79.0  14.0
6    71   56   95   80   93  395  79.0  14.0
34   84   70   56   96   87  393  78.6  16.0
49   89   84   54   85   80  392  78.4  17.0
3    98   94   90   55   54  391  78.2  18.0
13   94   79   57   76   84  390  78.0  19.0
42   77   76   85   89   63  390  78.0  19.0
30   78   91   76   83   60  388  77.6  21.0
14   86  100   92   60   50  388  77.6  21.0
32   66   86   79   65   92  388  77.6  21.0
17   67   99   73   62   86  387  77.4  24.0
45   85   69   86   58   88  386  77.2  25.0
19   83   92   93   61   57  386  77.2  25.0
7    64   86   75   60   99  384  76.8  27.0
24   89   94   65   59   77  384  76.8  27.0
39   51   89   88   89   65  382  76.4  29.0
31  100   97   70   58   55  380  76.0  30.0
43   72   54   74   82   97  379  75.8  31.0
11   78   61   94   53   93  379  75.8  31.0
4    83   70   66   88   69  376  75.2  33.0
36   52   97   94   66   65  374  74.8  34.0
15   57   64   95   62   89  367  73.4  35.0
44   80   51   79   56  100  366  73.2  36.0
37   68   94   54   80   68  364  72.8  37.0
46   83   52   84   66   77  362  72.4  38.0
26  100   53   71   68   69  361  72.2  39.0
2    68   55   73   75   89  360  72.0  40.0
47   55   86   60   82   71  354  70.8  41.0
23   76   67   60   87   62  352  70.4  42.0
27   51   86   77   82   56  352  70.4  42.0
40   95   54   63   78   62  352  70.4  42.0
8    95   77   63   52   56  343  68.6  45.0
22   92   57   59   63   70  341  68.2  46.0
9    50   52   88   51   87  328  65.6  47.0
38   53   97   59   51   67  327  65.4  48.0
50   58   53   75   59   81  326  65.2  49.0
18   54   82   68   50   63  317  63.4  50.0

In [29]:
#班排前五
scores_sorted_df.iloc[:5,:]

學科   國   英    數   社   自   總分    平均   排名
學號
21  94  83   78  72  95  422  84.4  1.0
48  77  70  100  90  85  422  84.4  1.0
12  72  83   85  82  97  419  83.8  3.0
10  56  93   96  83  89  417  83.4  4.0
16  82  98   79  60  95  414  82.8  5.0

In [31]:
#班排後五
scores_sorted_df.iloc[-5:,:]

學科   國   英   數   社   自   總分    平均    排名
學號
22  92  57  59  63  70  341  68.2  46.0
9   50  52  88  51  87  328  65.6  47.0
38  53  97  59  51  67  327  65.4  48.0
50  58  53  75  59  81  326  65.2  49.0
18  54  82  68  50  63  317  63.4  50.0